import {
  AppItem,
  ThemePreset,
  DockItem,
  TelegramChannel,
  ChangelogEntry,
  UserSettings,
} from './types';

// ─── Default User Settings ────────────────────────────────────────────────────

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'dark-blue',
  customTheme: {
    primary: '#3b82f6',
    secondary: '#1e40af',
    accent: '#60a5fa',
    surface: 'rgba(15, 23, 42, 0.85)',
    surface2: 'rgba(30, 41, 59, 0.7)',
    text: '#f1f5f9',
    textMuted: '#94a3b8',
    bgColor: '#0f172a',
    bgType: 'solid',
    bgGradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
  },
  language: 'ru',
  useProxy: false,
  proxyUrl: '',
  particlesEnabled: true,
  particleColor: '#3b82f6',
  particleCount: 80,
  particleSpeed: 0.5,
  showDock: true,
  dockPosition: 'bottom',
  widgets: {
    clock: true,
    weather: true,
    calendar: true,
    links: true,
    telegram: true,
  },
  hotkeys: {
    openSettings: 'Comma',
    openSearch: 'KeyF',
    goHome: 'Escape',
  },
  showSeconds: true,
  weatherCity: 'Moscow',
  weatherApiKey: '',
  startupAnimation: true,
  blurEnabled: true,
};

// ─── Theme Presets ────────────────────────────────────────────────────────────

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'dark-blue',
    name: 'Dark Blue',
    primary: '#3b82f6',
    secondary: '#1e40af',
    accent: '#60a5fa',
    surface: 'rgba(15, 23, 42, 0.85)',
    surface2: 'rgba(30, 41, 59, 0.7)',
    text: '#f1f5f9',
    textMuted: '#94a3b8',
    bgColor: '#0f172a',
    bgType: 'solid',
  },
  {
    id: 'dark-purple',
    name: 'Dark Purple',
    primary: '#7c3aed',
    secondary: '#4c1d95',
    accent: '#a78bfa',
    surface: 'rgba(15, 10, 30, 0.85)',
    surface2: 'rgba(30, 20, 60, 0.7)',
    text: '#f5f3ff',
    textMuted: '#a78bfa',
    bgColor: '#0f0a1e',
    bgType: 'solid',
  },
  {
    id: 'dark-green',
    name: 'Hacker Green',
    primary: '#10b981',
    secondary: '#065f46',
    accent: '#34d399',
    surface: 'rgba(5, 15, 10, 0.85)',
    surface2: 'rgba(10, 30, 20, 0.7)',
    text: '#ecfdf5',
    textMuted: '#6ee7b7',
    bgColor: '#050f0a',
    bgType: 'solid',
  },
  {
    id: 'dark-red',
    name: 'Dark Red',
    primary: '#ef4444',
    secondary: '#7f1d1d',
    accent: '#f87171',
    surface: 'rgba(20, 5, 5, 0.85)',
    surface2: 'rgba(40, 10, 10, 0.7)',
    text: '#fef2f2',
    textMuted: '#fca5a5',
    bgColor: '#140505',
    bgType: 'solid',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    primary: '#6366f1',
    secondary: '#312e81',
    accent: '#818cf8',
    surface: 'rgba(8, 8, 20, 0.9)',
    surface2: 'rgba(15, 15, 35, 0.7)',
    text: '#e0e7ff',
    textMuted: '#a5b4fc',
    bgColor: '#080814',
    bgType: 'gradient',
    bgGradient: 'linear-gradient(135deg, #080814 0%, #12102a 100%)',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    primary: '#0ea5e9',
    secondary: '#0c4a6e',
    accent: '#38bdf8',
    surface: 'rgba(5, 20, 35, 0.85)',
    surface2: 'rgba(10, 35, 60, 0.7)',
    text: '#f0f9ff',
    textMuted: '#7dd3fc',
    bgColor: '#05101f',
    bgType: 'gradient',
    bgGradient: 'linear-gradient(135deg, #05101f 0%, #0c2340 100%)',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    primary: '#f59e0b',
    secondary: '#92400e',
    accent: '#fbbf24',
    surface: 'rgba(25, 10, 5, 0.85)',
    surface2: 'rgba(45, 20, 10, 0.7)',
    text: '#fffbeb',
    textMuted: '#fcd34d',
    bgColor: '#190a05',
    bgType: 'gradient',
    bgGradient: 'linear-gradient(135deg, #190a05 0%, #2d1006 100%)',
  },
  {
    id: 'neon',
    name: 'Neon',
    primary: '#00ff88',
    secondary: '#00cc66',
    accent: '#ff0080',
    surface: 'rgba(0, 5, 15, 0.9)',
    surface2: 'rgba(0, 10, 25, 0.7)',
    text: '#e0ffe8',
    textMuted: '#00ff88',
    bgColor: '#00050f',
    bgType: 'solid',
  },
];

// ─── Dock Items ───────────────────────────────────────────────────────────────

export const DOCK_ITEMS: DockItem[] = [
  { id: 'home', name: 'Главная', icon: '🏠', action: 'none' },
  { id: 'settings', name: 'Настройки', icon: '⚙️', action: 'modal', target: 'fullSettings' },
  { id: 'telegram', name: 'Telegram', icon: '✈️', action: 'modal', target: 'telegram' },
  { id: 'weather', name: 'Погода', icon: '🌤️', action: 'modal', target: 'weather' },
  { id: 'changelog', name: 'Обновления', icon: '📋', action: 'modal', target: 'changelog' },
  { id: 'privacy', name: 'Конфиденциальность', icon: '🔒', action: 'modal', target: 'privacy' },
];

// ─── Quick Links / Dashboard Cards ───────────────────────────────────────────

export const QUICK_LINKS: AppItem[] = [
  {
    id: 'google',
    name: 'Google',
    icon: '🔍',
    url: 'https://www.google.com',
    category: 'Поиск',
    proxySupported: false,
  },
  {
    id: 'yandex',
    name: 'Яндекс',
    icon: '🔴',
    url: 'https://www.yandex.ru',
    category: 'Поиск',
    proxySupported: false,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    icon: '▶️',
    url: 'https://www.youtube.com',
    category: 'Медиа',
    proxySupported: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: '🐙',
    url: 'https://www.github.com',
    category: 'Разработка',
    proxySupported: false,
  },
  {
    id: 'reddit',
    name: 'Reddit',
    icon: '🟠',
    url: 'https://www.reddit.com',
    category: 'Сообщества',
    proxySupported: true,
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: '💬',
    url: 'https://www.discord.com',
    category: 'Общение',
    proxySupported: true,
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: '🎮',
    url: 'https://www.twitch.tv',
    category: 'Медиа',
    proxySupported: true,
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    icon: '🐦',
    url: 'https://www.x.com',
    category: 'Социальные сети',
    proxySupported: true,
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: '📷',
    url: 'https://www.instagram.com',
    category: 'Социальные сети',
    proxySupported: true,
  },
  {
    id: 'vk',
    name: 'ВКонтакте',
    icon: '🔵',
    url: 'https://vk.com',
    category: 'Социальные сети',
    proxySupported: false,
  },
  {
    id: 'wikipedia',
    name: 'Википедия',
    icon: '📖',
    url: 'https://ru.wikipedia.org',
    category: 'Образование',
    proxySupported: false,
  },
  {
    id: 'spotify',
    name: 'Spotify',
    icon: '🎵',
    url: 'https://www.spotify.com',
    category: 'Медиа',
    proxySupported: true,
  },
];

// ─── Telegram Channels ────────────────────────────────────────────────────────

export const TELEGRAM_CHANNELS: TelegramChannel[] = [
  {
    id: 'linkerru',
    name: 'LinkerRu',
    handle: '@linkerru',
    description: 'Официальный канал LinkerRu — новости, обновления и анонсы',
    url: 'https://t.me/linkerru',
    category: 'Официальный',
    verified: true,
  },
  {
    id: 'it_news',
    name: 'IT новости',
    handle: '@it_news_ru',
    description: 'Актуальные новости из мира технологий и IT',
    url: 'https://t.me/it_news_ru',
    category: 'Технологии',
  },
  {
    id: 'cybersec',
    name: 'Кибербезопасность',
    handle: '@cybersec_ru',
    description: 'Новости и советы по информационной безопасности',
    url: 'https://t.me/cybersec_ru',
    category: 'Безопасность',
  },
  {
    id: 'dev_tips',
    name: 'Dev Tips',
    handle: '@dev_tips_ru',
    description: 'Советы и трюки для разработчиков',
    url: 'https://t.me/dev_tips_ru',
    category: 'Разработка',
  },
  {
    id: 'proxy_news',
    name: 'Proxy & VPN',
    handle: '@proxy_vpn_news',
    description: 'Новости о прокси-серверах и VPN-сервисах',
    url: 'https://t.me/proxy_vpn_news',
    category: 'Инструменты',
  },
  {
    id: 'gaming_news',
    name: 'Gaming',
    handle: '@gaming_news_ru',
    description: 'Новости игровой индустрии',
    url: 'https://t.me/gaming_news_ru',
    category: 'Игры',
  },
];

// ─── Changelog ────────────────────────────────────────────────────────────────

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '12.0.0',
    date: '2025-07-10',
    type: 'major',
    changes: [
      'Полный редизайн интерфейса в современном стиле',
      'Новая система тем с цветовым микшером',
      'Переход на React + TypeScript + Next.js',
      'Анимированный фон с частицами (ParticleCanvas)',
      'Полностью переработанная панель настроек',
      'Новая система модальных окон',
      'Горячие клавиши для быстрого доступа',
      'Поддержка прокси-ссылок для заблокированных сайтов',
      'Интеграция с Telegram каналами',
      'Виджеты: часы, погода, календарь',
      'Сохранение настроек в localStorage',
      'Полная адаптация под мобильные устройства',
    ],
  },
  {
    version: '11.3.0',
    date: '2025-03-15',
    type: 'minor',
    changes: [
      'Добавлены новые прокси-серверы',
      'Исправлена работа виджета погоды',
      'Улучшена производительность частиц',
      'Добавлена поддержка системной темы',
    ],
  },
  {
    version: '11.2.0',
    date: '2025-01-20',
    type: 'minor',
    changes: [
      'Новые быстрые ссылки в панели',
      'Исправлены ошибки локализации',
      'Улучшена анимация dock-панели',
    ],
  },
  {
    version: '11.0.0',
    date: '2024-10-05',
    type: 'major',
    changes: [
      'Первый релиз версии 11',
      'Новый интерфейс панели управления',
      'Расширенные настройки темы',
    ],
  },
];
